---
- name: build docker image
  hosts: localhost
  vars:
    wipe: false
    i_state: '{{ "absent" if wipe == "true" else "present" }}'
  tasks:
    - name: build toy image
      docker_image:
        path: .
        name: toy
        tag: latest
        state: '{{ i_state }}'
        pull: no
        force: true
    - name: build this-errors-out image
      docker_image:
        path: ./this-errors-out/
        name: this-always-works
        tag: latest
        nocache: yes
        state: '{{ i_state }}'
        pull: no
        force: true
    - name: build secrets image
      docker_image:
        path: ./secrets
        name: secret-image
        tag: latest
        state: '{{ i_state }}'
        pull: no
        force: true
    - name: build fat image
      docker_image:
        path: ./layering
        name: fat
        dockerfile: Dockerfile.fat
        tag: latest
        state: '{{ i_state }}'
        pull: no
        force: true
    - name: build slim image
      docker_image:
        path: ./layering
        name: slim
        dockerfile: Dockerfile.slim
        tag: latest
        state: '{{ i_state }}'
        pull: no
        force: true
    - name: build current-date image
      docker_image:
        path: ./cache
        name: current-date
        tag: latest
        state: '{{ i_state }}'
        pull: no
        force: true
