---
- name: build images for the workshop
  hosts: localhost
  remote_user: root
  become: yes
  become_method: sudo
  vars:
    wipe: false
    i_state: '{{ "absent" if wipe == "true" else "present" }}'
  tasks:
    - name: build base image
      docker_image:
        path: base
        name: base
        tag: latest
        state: '{{ i_state }}'
        pull: no
        force: true
    - name: build this-errors-out image
      docker_image:
        path: ./this-errors-out/
        name: this-always-works
        tag: latest
        nocache: yes
        state: '{{ i_state }}'
        pull: no
        force: true
    - name: build secrets image
      docker_image:
        path: ./secrets
        name: secret-image
        tag: latest
        state: '{{ i_state }}'
        pull: no
        force: true
    - name: build fat image
      docker_image:
        path: ./layering
        name: fat
        dockerfile: Dockerfile.fat
        tag: latest
        state: '{{ i_state }}'
        pull: no
        force: true
    - name: build slim image
      docker_image:
        path: ./layering
        name: slim
        dockerfile: Dockerfile.slim
        tag: latest
        state: '{{ i_state }}'
        pull: no
        force: true
    - name: build current-date image
      docker_image:
        path: ./cache
        name: current-date
        tag: latest
        state: '{{ i_state }}'
        pull: no
        force: true
    - name: pull nginx image
      docker_image:
        name: modularitycontainers/nginx
        tag: latest
        state: '{{ i_state }}'
        pull: yes
    - name: pull postgresql image
      docker_image:
        name: registry.access.redhat.com/rhscl/postgresql-95-rhel7
        tag: latest
        state: '{{ i_state }}'
        pull: yes
